services:
  db:
    image: postgres:latest
    container_name: efo_postgres
    environment:
      POSTGRES_DB: efo_db
      POSTGRES_USER: efo_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
