# Generated by Django 5.1.2 on 2024-10-16 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iri', models.URLField(unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('gwas_trait', models.BooleanField(default=False)),
                ('ontology_name', models.CharField(max_length=100)),
                ('ontology_prefix', models.CharField(max_length=50)),
                ('ontology_iri', models.URLField()),
                ('is_obsolete', models.BooleanField(default=False)),
                ('is_defining_ontology', models.BooleanField(default=False)),
                ('has_children', models.BooleanField(default=False)),
                ('is_root', models.BooleanField(default=False)),
                ('short_form', models.CharField(max_length=50)),
                ('obo_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='efo_app.term')),
                ('synonyms', models.ManyToManyField(blank=True, related_name='terms', to='efo_app.synonym')),
                ('term_replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_terms', to='efo_app.term')),
            ],
        ),
    ]
